---
title: "Code_projet"
format: html
---

# Library

```{r}
install.packages(c("FactoMineR", "factoextra"))

library(FactoMineR)
library(factoextra)
library(ggplot2)
library(dplyr)
library(scales)
```

# Création de notre base données

```{r}
donnees <- readRDS("stu_qqq.rds")
```

```{r}
str(donnees)
```

```{r}
variables_final <- data.frame()
```

```{r}
variables_final <- data.frame(ST347Q01JA = donnees$ST347Q01JA, #ordi
                              ST250Q02JA = donnees$ST250Q02JA, #chambre
                              ST259Q01JA = donnees$ST259Q01JA, #note famille
                              ST260Q01JA = donnees$ST260Q01JA, #redoubler primaire
                              ST260Q02JA = donnees$ST260Q02JA, #redoubler collège
                              ST260Q03JA = donnees$ST260Q03JA, #redoubler lycée
                              ST062Q01TA = donnees$ST062Q01TA, #manquer 3 mois cours pri
                              ST062Q02TA = donnees$ST062Q02TA, #manquer 3 mois cours collège
                              ST062Q03TA = donnees$ST062Q03TA, #manquer 3 mois cours lycée
                              ST295Q02JA = donnees$ST295Q02JA, #etudier sur 30 derniers jours
                              ST295Q04JA = donnees$ST295Q04JA, #travailler 30 derniers jours
                              ST295Q05JA = donnees$ST295Q05JA, #travailler 30 derniers jours
                              ST307Q07JA = donnees$ST307Q07JA, #arrete devoir si trop long
                              ST345Q02JA = donnees$ST345Q02JA, #more relax than people
                              ST016Q01NA = donnees$ST016Q01NA, #satisfaction globale
                              ST296Q04JA = donnees$ST296Q04JA, #temps total passé sur les devoirs
                              ST292Q01JA = donnees$ST292Q01JA, #s'inquiète de la difficulté des maths
                              ST297Q09JA = donnees$ST297Q09JA, #participation à des cours supplémentaires de maths
                              ST337Q07JA = donnees$ST337Q07JA, #science club dans l'école
                              ST338Q07JA = donnees$ST338Q07JA, #science club en dehors de l'école
                              ST300Q01JA = donnees$ST300Q01JA, #parents parle de à quel point tu es bon à l'école
                              ST300Q04JA = donnees$ST300Q04JA, #parents parlent de l'importance de compléter le lycee
                              ST300Q06JA = donnees$ST300Q06JA, #parents parlent de à quel points tu t'entends avce les autres
                              ST300Q07JA = donnees$ST300Q07JA, #parents t'encouragent à avoir des bonnes notes
                              ST300Q09JA = donnees$ST300Q09JA, #parents parlent de ton éducation
                              ST327Q01JA = donnees$ST327Q01JA, #prévu de complèter ISCED 2
                              ST327Q02JA = donnees$ST327Q02JA, #prévu de complèter ISCED 3.3
                              ST327Q03JA = donnees$ST327Q03JA, #prévu de complèter ISCED 3.4
                              ST327Q04JA = donnees$ST327Q04JA, #prévu de complèter ISCED 4
                              ST327Q05JA = donnees$ST327Q05JA, #prévu de complèter ISCED 5
                              ST327Q06JA = donnees$ST327Q06JA, #prévu de complèter ISCED 6
                              ST327Q07JA = donnees$ST327Q07JA, #prévu de complèter ISCED 7
                              ST327Q08JA = donnees$ST327Q08JA, #prévu de complèter ISCED 8

                              
                              ST347Q01JA = donnees$ST347Q01JA,
                              ST350Q01JA = donnees$ST350Q01JA
                              )
```

```{r}
var_final_clean <- na.omit(variables_final)
```

# Graphiques

```{r}
donnees_graph <- var_final_clean %>%
  select(Fermeture = ST347Q01JA, Apprentissage = ST350Q01JA) %>%
  na.omit() %>%
  mutate(
    Fermeture = factor(Fermeture, 
                       levels = c(1, 2, 3, 4, 5, 6),
                       # Labels raccourcis pour éviter la rotation du texte
                       labels = c("Non", "< 1 mois", "1-3 mois", 
                                  "3-6 mois", "6-12 mois", "> 1 an")),
    Apprentissage = factor(Apprentissage,
                           levels = c(1, 2, 3),
                           labels = c("Moins", "Autant", "Plus")) # Labels simplifiés
  ) %>%
  count(Fermeture, Apprentissage) %>%
  group_by(Fermeture) %>%
  mutate(Pourcentage = n / sum(n))

# 2. Graphique Épuré
ggplot(donnees_graph, aes(x = Fermeture, y = Pourcentage, fill = Apprentissage)) +
  
  # Barres
  geom_bar(stat = "identity", position = "fill", width = 0.6) + # width réduit pour l'élégance
  
  # Texte (On cache les pourcentages < 3% pour éviter la surcharge)
  geom_text(aes(label = ifelse(Pourcentage > 0.03, percent(Pourcentage, accuracy = 1), "")), 
            position = position_fill(vjust = 0.5), 
            color = "white", size = 3.5, fontface = "bold") +
  
  # Couleurs
  scale_fill_manual(values = c("#D9534F", "#AAAAAA", "#5BC0DE")) +
  
  # Axes
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  
  # Textes et Titres
  labs(
    title = "Impact de la fermeture des écoles sur l'apprentissage",
    subtitle = "Perception des élèves comparée aux cours en présentiel",
    caption = stringr::str_wrap("Note de lecture: Dans les écoles qui on été fermées durant  moins d'un mois dû au covid, 56% pourcent des élèves considère avoir moins appris que en présentiel, 33% autant et 11% mieux.", width = 100),
    x = NULL, # On enlève le titre X car les labels "1-3 mois" sont explicites
    y = NULL, # On enlève le titre Y car les % sont explicites
    fill = NULL # On enlève le titre de la légende
  ) +
  
  # Thème Minimaliste
  theme_minimal(base_size = 12) +
  theme(
    
    # Suppression des éléments inutiles
    panel.grid.major.x = element_blank(), # Pas de lignes verticales
    panel.grid.minor = element_blank(),   # Pas de petites lignes
    panel.grid.major.y = element_line(color = "grey90"), # Lignes horizontales très discrètes
    
    # Gestion de la légende
    legend.position = "top", 
    legend.justification = "left",
    legend.margin = margin(t = 0, b = 0),
    
    # Gestion des titres
    plot.title.position = "plot", # Aligne le titre sur l'image entière
    plot.title = element_text(face = "bold", size = 16, color = "#333333"),
    plot.caption = element_text(hjust=0, color = "#666666" ),
    plot.subtitle = element_text(size = 12, color = "#666666", margin = margin(b = 20)),
    
    plot.margin = margin(t = 0.5, r = 0.5, b = 1, l = 0.5, "cm"),
    # Gestion des axes
    axis.text.x = element_text(color = "black", margin = margin(t = 5)),
    axis.text.y = element_text(color = "black")
  )
```

```{r}
cor(var_final_clean$ST347Q01JA, var_final_clean$ST350Q01JA)
```

coefficiant de corrélation quasi nul

```{r}
print("--- RÉSULTAT DU TEST CHI-DEUX ---")
test_chi2 <- chisq.test(table(var_final_clean$ST347Q01JA, var_final_clean$ST350Q01JA))
print(test_chi2)
```

# ACM

```{r}
str(var_final_clean)
```

Variable type num, besoin convertir en type factor pour ACM

```{r}
cols_a_convertir <- c(1:16) 
var_final_clean[, cols_a_convertir] <- lapply(var_final_clean[, cols_a_convertir], as.factor)
```

```{r}
res.mca <- MCA(var_final_clean, graph = FALSE)
print(res.mca)
```

```{r}
# Visualiser l'éboulis des valeurs propres
fviz_eig(res.mca, addlabels = TRUE, ylim = c(0, 15))
```

```{r}
# Carte des variables (les catégories)
fviz_mca_var(res.mca, 
             choice = "mca.cor", # Correlation entre variables et axes
             repel = TRUE,       # Évite le chevauchement de texte
             ggtheme = theme_minimal())
```

```{r}
fviz_mca_ind(res.mca, 
             axes = c(1,2),
             col.ind = "cos2", # Qualité de représentation
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE)
```
